### ISSUE TITLE
Empty HTML helper

### ISSUE THREAD

**Issue by mlutze** [stephentetley/flix-htmldoc#3]
I'd like to produce an empty `<br/>` tag. I can do this: `br(Nil, Html(identity))`, but it seems invasive to deal with the continuation directly. I can probably also do `br(Nil, text(""))` or `br(Nil, concat(Nil))`, but these feel too indirect.

Can we get a clean `empty()` function?

**Comment by stephentetley** [comment]
Thanks Matthew, I'll look into it this evening.

**Comment by stephentetley** [comment]
I've added an `empty` function along with functions to make "void" elements with self closing tags. 

Packaged up as release v0.1.3
