### ISSUE TITLE
Extra spaces around text elements

### ISSUE THREAD

**Issue by mlutze** [stephentetley/flix-htmldoc#4]
I'd like to have inline links in my page. But it seems that extra spaces are added around text elements, which changes the displayed text. For example, if I want a comma-separated list of links:

```scala
    pub def test(): String = {
        Text.HtmlDoc.toString(
            Text.HtmlDoc.anchor(List#{Text.HtmlDoc.href_("example.com")}, Text.HtmlDoc.text("link1"))
            <&>
            Text.HtmlDoc.text(", ")
            <&>
            Text.HtmlDoc.anchor(List#{Text.HtmlDoc.href_("example.com")}, Text.HtmlDoc.text("link2"))
        )
    }
```

This produces
```html
<a href="example.com"> link1 </a>                                               
, 
<a href="example.com"> link2 </a>
```

And the resulting output looks like:
```text
link1 , link2
```

(Note the extra space before the comma)

**Comment by stephentetley** [comment]
Thanks Matthew, I'll look into it this evening.

A quick thought though - does it work properly if you put the sequence within an outer tag of some kind?

**Comment by mlutze** [comment]
Do you mean something like this?

```scala
    pub def test(): String = {
        Text.HtmlDoc.toString(
            Text.HtmlDoc.paragraph(Nil, 
                Text.HtmlDoc.anchor(List#{Text.HtmlDoc.href_("example.com")}, Text.HtmlDoc.text("link1"))
                <&>
                Text.HtmlDoc.text(", ")
                <&>
                Text.HtmlDoc.anchor(List#{Text.HtmlDoc.href_("example.com")}, Text.HtmlDoc.text("link2"))
            )
        )
    }
```

yields

```html
<p> <a href="example.com"> link1 </a>                                           
, 
<a href="example.com"> link2 </a> </p>
```

**Comment by stephentetley** [comment]
Thanks Matthew - yes that's what I meant. I wondered if it was a problem being a sequence and not a node with children, but as it didn't change anything it looks like the HTML combinator `<&>` is not being translated to the right Pretty Print combinator.

**Comment by stephentetley** [comment]
I've made a new release that stops adding visible spacing by default. It also changes the render to use `hcat` rather than `vcat` which will mean the output is more compact. This would be obvious opening the file in an editor but should not affect browser rendering.

If you want a separating space between HTML elements there is a new combinator `<&&>`.

**Comment by mlutze** [comment]
Works well. Thanks, Stephen!
